config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tracks#index'
  resources :tracks, except: %i[edit update destroy] do
    get :compare, on: :collection
  end
  namespace :api do
    namespace :v1 do
      resources :tracks, only: %i[show index] do
        get :compare, on: :collection
        resources :points, only: %i[index] do
          get :for_map, on: :collection
        end
      end
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/point.rb
# frozen_string_literal: true

class Point < ApplicationRecord
  belongs_to :track

  scope :uniq_by_displacement, -> { where(uniq_by_displacement: true) }
end

app/models/track.rb
# frozen_string_literal: true

class Track < ApplicationRecord
  belongs_to :user
  has_many :points, dependent: :destroy
  before_create -> { self.uuid = SecureRandom.base64 }

  validates :track_attachment, presence: true

  mount_uploader :track_attachment, TrackAttachmentUploader

  accepts_nested_attributes_for :points

  def name
    "#{File.basename(track_attachment.path)} - #{uuid}"
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Clearance::User

  has_many :tracks, dependent: :destroy
end

app/controllers/api/v1/base_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class BaseController < ActionController::API
      include Api::BlueprinterAutoviews
    end
  end
end

app/controllers/api/v1/points_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class PointsController < BaseController
      blueprinter_views_for :point

      def index
        @points = parent.points.uniq_by_displacement
        render json: PointBlueprint.render(@points, view: view)
      end

      private

      def parent
        @parent ||= Track.find(params[:track_id])
      end
    end
  end
end

app/controllers/api/v1/tracks_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class TracksController < BaseController
      blueprinter_views_for :track

      def show
        render json: TrackBlueprint.render(resource, view: view)
      end

      def index
        @tracks = Track.all
        render json: TrackBlueprint.render(@tracks, view: view)
      end

      def compare
        @track1 = Track.includes(:points).find(params[:track1])
        @track2 = Track.includes(:points).find(params[:track2])
        @comparison_result = Tracks::Compare.new(@track1, @track2).call

        render json: {
          points: PointBlueprint.render_as_hash(@comparison_result[:points]),
          similarity: @comparison_result[:similarity]
        }
      end

      private

      def resource
        @resource ||= Track.find(params[:id])
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/concerns/api/blueprinter_autoviews.rb
# frozen_string_literal: true

module Api
  module BlueprinterAutoviews
    VIEW_FALLBACK = :default
    extend ActiveSupport::Concern

    included do
      def self.blueprinter_views_for(model, view_fallback: VIEW_FALLBACK)
        blueprinter_class = "#{model.to_s.capitalize}Blueprint".constantize
        define_method :view do
          blueprinter_class::VIEWS.find do |view|
            view.to_s == params[:view]
          end || view_fallback
        end
      end
    end
  end
end

app/controllers/tracks_controller.rb
# frozen_string_literal: true

class TracksController < ApplicationController
  before_action :require_login, only: %i[
    new create compare
  ]

  def index
    @tracks = Track.order(:id).page(params[:page])
  end

  def show
    @track  = Track.includes(:points).find(params[:id])
    @points = @track.points.page(params[:page])
  end

  def compare
    @tracks = Track.all
  end

  def new
    @errors = {}
  end

  def create
    transaction = Tracks::CreateTrack.new
    transaction.call(permitted_params) do |result|
      result.success do |track|
        redirect_to track_path(track)
      end
      result.failure do |errors|
        @errors = errors
        render :new
      end
    end
  end

  private

  def permitted_params
    params.fetch(:track, {})
          .permit(:track_attachment)
          .merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def display_errors(field, error_entity)
    if error_entity.is_a?(String)
      error_entity
    elsif error_entity.is_a?(Array)
      "#{field.to_s.humanize} #{error_entity.join(', ')}."
    else
      raise ArgumentError, 'Cannot process anything but Array or String.'
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Simiroute
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag "https://maps.googleapis.com/maps/api/js"
    = yield :js
  %body
    %body
    %header.navbar
      %section.navbar-section
        = link_to "Simiroute", root_path, class: "nav-brand text-bold mr-2 text-large text-uppercase"
      %section.navbar-center
        %div.bg-primary{style: "margin: 2em; padding: 1em"}
          %i.icon.icon-4x.icon-photo
      %section.navbar-section
        - if signed_in?
          = link_to "Sign out", sign_out_path, class: "btn btn-link", method: :delete
        - else
          = link_to "Sign in", sign_in_path, class: "btn btn-link"
          = link_to "Sign up", sign_up_path, class: "btn btn-link"
    %div{class: "container", style: "margin-top: 5em; margin-bottom: 5em;"}
      = yield

app/views/tracks/compare.html.haml
.columns
  .column.col-10.col-mx-auto
    .col-12
      = link_to "Back", tracks_path, class: "btn"
  .column.col-10.col-mx-auto
    .col-12
      #map-container
        #map-canvas
    .col-12
      %h1
        Track similarity is
        %span#similarity
          yet unknown.
      .form-group
        .col-9
          = select_tag "track1", options_from_collection_for_select(@tracks, :id, :name), id: "select-track1"
        .col-9
          = select_tag "track2", options_from_collection_for_select(@tracks, :id, :name), id: "select-track2"
      .form-group
        .col-12
          = submit_tag "Compare tracks", class: "btn btn-primary", id: "compare-track"

= content_for :js do
  = javascript_include_tag "maps/tracks/compare"

app/views/tracks/index.html.haml
%div{class: "columns"}
  %div{class: "column col-10 col-mx-auto"}
    %table{class:"table"}
      %thead
        %tr
          %th{colspan: 5}
            - if signed_in?
              = link_to "Add track", new_track_path, class: "btn btn-primary"
              = link_to "Compare tracks", compare_tracks_path, class: "btn btn-primary"
        %tr
          %th Id
          %th Uuid
          %th Created at
          %th Updated at
          %th User email
          %th View
      %tbody
        - @tracks.each do |track|
          %tr
            %td= track.id
            %td= track.uuid
            %td= track.created_at
            %td= track.updated_at
            %td= track.user.email
            %td
              =link_to track_path(track), class: "btn btn-primary" do
                %i{class: "icon icon-more-vert"}
    = paginate @tracks

app/views/tracks/new.html.haml
.columns
  .column.col-3.col-mx-auto
    .panel{style: "padding: 1em"}
      .panel-header
        .panel-title
          %h2.text-center Create Track
      .panel-nav
        = image_tag "map", style: "height: 20em", class: "p-centered"
        %p.text-center Here you can save your tracks. Remember that tracks are submitted in form of .gpx or .kml format.
      .panel-body
        = form_for Track.new, html: { class: "form-horizontal" } do |f|
          .form-group
            .col-3
              %label{class: "form-label", for: "track_attachment"} Track file
            .col-9
              = f.file_field :track_attachment,
                class: "form-input #{@errors[:track_attachment] ? 'is-error' : ''}"
              - if @errors[:track_attachment]
                %p{class: "form-input-hint"}
                  = display_errors(:track_attachment, @errors[:track_attachment])
          .form-group
            .col-12
              = f.submit "Submit track file", class: "btn btn-primary"
      .panel-footer
        .divider
        = link_to "Back", tracks_path, class: "btn"

app/views/tracks/show.html.haml
.columns
  .column.col-10.col-mx-auto
    .col-12
      = link_to "Back", tracks_path, class: "btn"
  .column.col-10.col-mx-auto
    .col-12
      #map-container
        #map-canvas
  .column.col-10.col-mx-auto
    .col-12
      %h1
        Track
        = @track.uuid
      %div
        = link_to @track.track_attachment.identifier,
          @track.track_attachment.url
        %p
          Distance
          = @track.distance
      %table.table
        %thead
          %tr
            %th Position
            %th Altitude
            %th Longitude
            %th Latitude
            %th Tracked at
            %th Displacement sequence
        %tbody
          - i = (@points.size * ((params[:page] || 1).to_i - 1)) + 1
          - @points.zip(i..(i + @points.size)).each do |point, position|
            %tr
              %td= position
              %td= point.altitude
              %td= point.lng
              %td= point.lat
              %td= point.tracked_at
              %td= point.displacement_sequence
    .col-12
      = paginate @points

= content_for :js do
  = javascript_include_tag "maps/tracks/show"

app/views/users/_form.html.haml
.form-group
  .col-3
    = form.label :email, class: 'form-label'
  .col-9
    = form.text_field :email, type: 'email', class: 'form-input'
.form-group
  .col-3
    = form.label :password, class: 'form-label'
  .col-9
    = form.password_field :password, class: 'form-input'

app/views/users/new.html.haml
.columns
  .column.col-3.col-mx-auto
    .panel{style: "padding: 1em"}
      .panel-header
        .panel-title
          %h2.text-center= t(".title")
      .panel-body
        = form_for @user, html: { class: "form-horizontal" } do |form|
          = render partial: '/users/form', object: form
          .form-group
            .col-12
              = form.submit nil, class: "btn btn-primary"
      .panel-footer
        .divider
        = link_to "Back", tracks_path, class: "btn"
        = link_to t(".sign_in"), sign_in_path, class: "btn"